# Generated by Django 3.2.11 on 2022-01-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory_API', '0002_product_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenizedPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_capture', models.TextField()),
                ('token_updated_time', models.TimeField()),
                ('token_life', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='instock',
            new_name='delete_now',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
