# Generated by Django 3.2.11 on 2022-01-16 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TokenCreator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenmanagement',
            name='token_capture',
        ),
    ]
