# Generated by Django 3.2.11 on 2022-01-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TokenCreator', '0002_remove_tokenmanagement_token_capture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenManagement',
        ),
    ]
