# Generated by Django 3.2.11 on 2022-01-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TokenCreator', '0003_delete_tokenmanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('in_stock', models.BooleanField(default=False)),
                ('delete_now', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
